### ISSUE TITLE
UI issue for status Updateform in iOS

### ISSUE THREAD

**Issue by emvigotech** [GetStream/react-native-activity-feed#51]
Initially the StatusUpdateForm is seen on the view. After adding a status through statusupdateform the view disappears and only the flatfeed can be seen.So after that we are not able to add new status. This issue only ocurs in iOS. This is working fine in android.

![IMG_0330](https://user-images.githubusercontent.com/26790656/62470723-ae70bc00-b7b8-11e9-8204-e04c412bc8f2.PNG)

react-native: 0.58.6,
MacOSX: Mojave
Xcode: 10.1
Device: iPhone 6

This is the style we are using:

<SafeAreaView style={{flex: 1}} forceInset={{ top: 'always' }}>
        <ScrollView style={{flex: 1}}>
        <StreamApp
             apiKey={apiKey}
             appId={appId}
             token={token}>
<StatusUpdateForm feedGroup="timeline" 
            onSuccess={() => {
         
            }}
          />
          <FlatFeed   
          Activity={(data) => (
        <Activity
          {...data}
          onPress={() => {
            this.props.navigation.navigate('SinglePost', {activityId: data.activity.id, user_id: this.props.auth.userId, apiKey: this.state.apiKey, appId: this.state.appId, token: this.state.token})}
            }
    
          Footer={
            
            <View>
            <View style={{ flexDirection: 'row', alignItems: 'center' }}> 
            <LikeButton reactionKind="like"  {...data} 
             
            />
            <ReactionIcon
              labelSingle="comment"
              labelPlural="comments"
              counts={data.activity.reaction_counts}
              kind="comment"
            />
          </View>
            <CommentList activityId={data.activity.id} />
            <CommentBox activity={data.activity} onAddReaction={data.onAddReaction} />
        </View>
          }
          />  )}
        />
          </StreamApp> 
          </ScrollView>
        </SafeAreaView>

**Comment by vishalnarkhede** [comment]
Hey @emvigotech ,

Could you try setting `noKeyboardAccessory={true}` prop on StatusUpdateForm component? That should fix the issue for now.

**Comment by emvigotech** [comment]
Thank u vishal. It worked like a charm :)

**Comment by vishalnarkhede** [comment]
Hey @emvigotech 

Have you followed these steps? https://github.com/GetStream/react-native-activity-feed#final-setup-steps-for-the-react-native-activity-feed-package

**Comment by emvigotech** [comment]
I had to link image-picker, but still the post is not updating real time.
The post added from status update form is not updating. 
It only gets updated after the page is rendered again..

This seems to be only issue remaining now
Thanks in advance

**Comment by jaapbakker88** [comment]
This is the issue concerning like and comment counts not updating in realtime right? I emailed you guys earlier realtime is not supported for reactions so I'm going to close this issue. Feel free to reply with any further issues to reopen this.
